[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Call me maybe: Return the most probable function with arguments from a single prompt and a list of function definitions."
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.40.0",
    "huggingface-hub>=0.20.0",
    "typer>=0.24.0",
    "mypy>=2.1.0",
    "dotenv>=0.9.9",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["llm_sdk"]
